# NOT REQUIRED NOW WE USE run_tests.py file INSTED OF THIS
#[pytest]
#addopts = --html=HtmlReport/report.html --alluredir=allure-results

[pytest]
markers =
    negative: marks tests as negative scenarios
    positive: marks tests as positive scenarios